config/routes.rb
Rails.application.routes.draw do
  get 'cart/index'

  resources :items
  root 'static_pages#home'

  get '/help', to: 'static_pages#help'

  get '/about', to: 'static_pages#about'
  
  get '/login', to: 'user#login'
  get '/logout', to: 'user#logout'
  
  get '/cart', to: 'cart#index'
  
  get '/cart/:id', to: 'cart#add'
  
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def index
    # pass the information to the view page of the cart
    
    if session[:cart] then
      @cart = session[:cart]
    else
      @cart = {}
    end
    
  end
  
  
  def add
    # get the id of the product we want to add
    
    id = params[:id]
    
    # if the session is already there use that, if not make a new session
    
    if session[:cart]
      cart = session[:cart]
    else
      session[:cart] = {}
      cart = session[:cart]
    end
    
    
    # if the product is already in the cart increase the quantity by 1
    
    if cart[id] then
      cart[id] = cart[id] + 1
    else
      cart[id] = 1
    end
    
    redirect_to :action => :index
    
  end
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:title, :description, :price, :image_url, :category, :brand)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  
  def login
    session[:login] = 1
    flash[:notice] = "You logged in..Well done!"
    redirect_to :controller => :items
    
  end
  
  
  
  
  
  
  def logout
    session[:login] = nil
    flash[:notice] = "Ok then see you next time!"
    redirect_to :controller => :items
  end
  
  
  
  
  
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/cart/index.html.erb
<p id="notice"><%= notice %></p>

<table id="customers">
  
  <% @cart.each do |id, quantity | %>
  
  <% item = Item.find_by_id(id) %>
  
  <tr>
    <td>
      <div class="image">
        <% link_to(image_tag item.image_url, :style => "height:40px"), item %>
      </div>
    </td>
    
    <td><%= link_to item.title, item %></td>
    <td><a href="#">Remove from cart</a></td>
    <td><%= number_to_currency(item.price, :unit => "€") %> </td>
    <td><%= quanity %></td>
    <td><%= number_to_currency(quantity * item.price, :unit => "€") %></td>
  </tr>
  
  <% end %>
  
</table>
  

app/views/items/_form.html.erb
<%= form_with(model: item, local: true) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :item_title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :item_description %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :item_price %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url, id: :item_image_url %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category, id: :item_category %>
  </div>

  <div class="field">
    <%= form.label :brand %>
    <%= form.text_field :brand, id: :item_brand %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<div id="itemsContainer">
  <h1>Items</h1>
  

    <% @items.each do |item| %>
    
      <div class="itemhols">
        <h1><%= item.title %></h1>
        
        <%= link_to (image_tag item.image_url, :class=> "itemholsIm"), item %>
        
        <p><%= item.description %></p>
        <p>Price <%= number_to_currency(item.price, :unit => "€") %>
        <br>
        Category: <%= item.category %>
        <br>
        Brand: <%= item.brand %>
        </p>
        
        <p>
        <%= link_to 'Show', item, :class =>"button", :role=>"button" %>
        
        <% if session[:login] == 1 %>
        
        <%= link_to 'Edit', edit_item_path(item), :class =>"button", :role=>"button" %>
        <%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' }, :class =>"button", :role=>"button" %>
        
        <% end %>
        
        </p>
        
        
      </div>
      
    <% end %>
  
</div>
<br>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>


<div id="itemsContainer">
  <h1><%= @item.title %></h1>
  
  <%= image_tag @item.image_url, :class => 'welcomeIm' %>
  <p><%= @item.description %><p>
    
  <div class="itemhols">
    
    <p><%= number_to_currency(@item.price, :unit => "€") %>
    <br>
    Category: <% @item.category %>
    <br>
    <%= @item.brand %>
    
    </p>
    
    <p>
      
      <%= link_to 'Edit', edit_item_path(@item), :class => "button", :role => "button" %> |
<%= link_to 'Back', items_path, :class => "button", :role => "button" %>
      
    </p>
    
  </div>
  
  
</div>

app/views/layouts/_footer.html.erb
<footer class="foot">Im the Footer</footer>

app/views/layouts/_header.html.erb
<header class="headSec">
      <h1>Peters Golf Store</h1>
      <ul>
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Items", items_path %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Help", help_path %></li>
        
        <% if session[:login] == 1 %>
        <li><%= link_to "Log Out", logout_path %></li>
        <% else %>
        <li><%= link_to "Log In", login_path %></li>
        <% end %>
        
        
      </ul>
    </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Building an app with Liam</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <%= render 'layouts/header' %>
    
    <div class="container">
    <%= yield %>
    </div>
    
    
    
    <%= render 'layouts/footer' %>
    
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>

<h1>About</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>

<h1>Help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>

<div class="mainCont">
  
  <%= image_tag("golf.jpg", alt: "welcome Logo", :class => "welcomIn") %>
  
  <h1>Home</h1>
  <p>Welcome to your first home page</p>
  <hr>
  <p>This will be the home page of the application we will create. We will work on this each week</p>

</div>